Array-Game-Winner-Rounds
Coding-Interview-Club/problem-solutions pull request #1
Opened 2020-10-18 04:45 UTC by rimesta21

Adding a solution to LeetCode challenge 1535. Find the Winner of an Array Game solved 10/16/20. This problem was introduced by Daniel G. Shanker.

2020-11-04 07:52 UTC, xm94 commented
Hey @rimesta21 ! Sorry for just now noticing this, it looks like you've accidentally pushed some IDE files, I can merge this in once you clear those up!

2020-11-04 07:54 UTC, xm94 requested changes

2020-11-04 07:54 UTC, xm94 commented on Array-Game-Rounds-Winner/src/main.java
> +}
So pretty much make the PR just contain this file, make sure to be careful with what you add when commiting

2020-11-05 01:18 UTC, rimesta21 commented
Hey, @xm94 so sorry about that! I think I have deleted all the files besides main. I will be more careful next time.

2020-11-05 01:21 UTC, xm94 approved these changes
Awesome, sounds good

2020-11-05 01:21 UTC, merged